/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *MainPage;
    QTextBrowser *contactNo;
    QPushButton *delno;
    QPushButton *btn_HomeNext;
    QLabel *label_6;
    QPushButton *update;
    QLabel *label_4;
    QTextBrowser *addressHome;
    QLabel *label_5;
    QLabel *label;
    QTableView *tableView;
    QTableWidget *main_table;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *getinfo;
    QTextBrowser *countryHome;
    QPushButton *addno;
    QPushButton *btn_HomePrev;
    QTextBrowser *aadharHome;
    QPushButton *history;
    QLabel *label_img;
    QTextBrowser *nameHome;
    QLabel *label_39;
    QTextBrowser *companyHome;
    QLabel *label_40;
    QPushButton *homePage_update;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *totContacts;
    QLabel *homePageNo;
    QWidget *PageDelNo;
    QLabel *label_32;
    QTableView *tableView_4;
    QPushButton *btn_delSubmit;
    QLabel *label_31;
    QLineEdit *delNoCode;
    QTextBrowser *delNoStatus;
    QLabel *label_30;
    QLabel *label_33;
    QPushButton *pushButton_15;
    QLabel *label_44;
    QLineEdit *delNumber;
    QLabel *label_45;
    QLineEdit *reconfirmCode;
    QLabel *label_46;
    QLineEdit *reconfirmNo;
    QLabel *label_47;
    QWidget *PageAddNo;
    QLabel *label_7;
    QComboBox *noType;
    QTextEdit *code;
    QTextEdit *company;
    QTextEdit *vipDigits;
    QTextEdit *aadharNo;
    QLabel *label_11;
    QLabel *label_8;
    QLabel *label_code;
    QLabel *label_10;
    QLabel *label_12;
    QPushButton *addNoSubmit;
    QPushButton *pushButton_16;
    QTextEdit *name;
    QLabel *label_37;
    QTextEdit *address;
    QLabel *label_41;
    QTextEdit *code_Name;
    QLabel *label_codeName;
    QWidget *PageGetInfo;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *infoSearch;
    QPushButton *pushButton_18;
    QLabel *label_51;
    QLabel *label_15;
    QLabel *label_17;
    QTextBrowser *contactNo_get;
    QLabel *totContacts_get;
    QLabel *label_19;
    QTableView *tableView_2;
    QTextBrowser *country_get;
    QLabel *label_18;
    QLabel *label_16;
    QTextBrowser *address_get;
    QTextBrowser *aadhar_get;
    QLabel *label_50;
    QTextBrowser *company_get;
    QTextBrowser *name_get;
    QTableWidget *getInfo_table;
    QLabel *label_48;
    QPushButton *btn_getInfoNext;
    QLabel *label_49;
    QPushButton *btn_getInfoPrev;
    QLabel *getInfoPageNo;
    QWidget *PageUpdate;
    QLabel *label_20;
    QTableView *tableView_3;
    QPushButton *submit_update;
    QLabel *label_26;
    QLineEdit *searchNo_update;
    QTextBrowser *status_update;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *pushButton_17;
    QLabel *label_53;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *label_52;
    QLabel *label_22;
    QLineEdit *searchCode_update;
    QLabel *label_updateCode;
    QLineEdit *country_update;
    QLineEdit *name_update;
    QLineEdit *company_update;
    QLineEdit *aadhar_update;
    QTextEdit *address_update;
    QWidget *PageHistory;
    QLabel *label_34;
    QTableWidget *historyTable;
    QPushButton *BtnPrevHistory;
    QPushButton *BtnNextHistory;
    QComboBox *retriveType;
    QLabel *label_35;
    QLineEdit *lowerTime;
    QLineEdit *upperTimeOrN;
    QLabel *labelTime;
    QLabel *label_N;
    QPushButton *BtnHistorySubmit;
    QPushButton *pushButton_14;
    QLabel *label_pageNo;
    QLabel *label_9;
    QLabel *label_36;
    QLabel *label_totalEntries;
    QWidget *page;
    QLabel *label_54;
    QTableView *tableView_5;
    QPushButton *login_submit;
    QLineEdit *login_pswd;
    QLabel *label_57;
    QLineEdit *login_userId;
    QLabel *label_55;
    QPushButton *pushButton_19;
    QPushButton *loginInfo_update;
    QWidget *page_2;
    QLabel *label_58;
    QTableView *tableView_6;
    QLineEdit *login_userId_new;
    QLineEdit *login_pswd_new;
    QLabel *label_56;
    QPushButton *loginUpdate_submit;
    QLabel *label_59;
    QPushButton *pushButton_20;
    QTextBrowser *msg;
    QLabel *label_38;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(799, 592);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243, 10);"));
        MainWindow->setToolButtonStyle(Qt::ToolButtonIconOnly);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(10, 30, 781, 571));
        stackedWidget->setAutoFillBackground(false);
        stackedWidget->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243, 10);"));
        MainPage = new QWidget();
        MainPage->setObjectName(QString::fromUtf8("MainPage"));
        contactNo = new QTextBrowser(MainPage);
        contactNo->setObjectName(QString::fromUtf8("contactNo"));
        contactNo->setGeometry(QRect(390, 180, 141, 31));
        contactNo->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        delno = new QPushButton(MainPage);
        delno->setObjectName(QString::fromUtf8("delno"));
        delno->setGeometry(QRect(140, 360, 121, 31));
        delno->setStyleSheet(QString::fromUtf8("background-color: rgb(237, 212, 0);\n"
"color: rgb(239, 41, 41);"));
        btn_HomeNext = new QPushButton(MainPage);
        btn_HomeNext->setObjectName(QString::fromUtf8("btn_HomeNext"));
        btn_HomeNext->setGeometry(QRect(570, 430, 61, 25));
        label_6 = new QLabel(MainPage);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(310, 350, 71, 17));
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        update = new QPushButton(MainPage);
        update->setObjectName(QString::fromUtf8("update"));
        update->setGeometry(QRect(140, 310, 121, 31));
        update->setStyleSheet(QString::fromUtf8("background-color: rgb(237, 212, 0);\n"
"color: rgb(239, 41, 41);"));
        label_4 = new QLabel(MainPage);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(320, 266, 67, 21));
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        addressHome = new QTextBrowser(MainPage);
        addressHome->setObjectName(QString::fromUtf8("addressHome"));
        addressHome->setGeometry(QRect(390, 380, 141, 31));
        addressHome->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_5 = new QLabel(MainPage);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(310, 390, 67, 17));
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        label = new QLabel(MainPage);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(170, 180, 67, 17));
        label->setStyleSheet(QString::fromUtf8("color: rgb(129, 247, 104);"));
        tableView = new QTableView(MainPage);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(290, 130, 421, 361));
        tableView->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        main_table = new QTableWidget(MainPage);
        if (main_table->columnCount() < 1)
            main_table->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        main_table->setHorizontalHeaderItem(0, __qtablewidgetitem);
        if (main_table->rowCount() < 8)
            main_table->setRowCount(8);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(0, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(1, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(2, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(3, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(4, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(5, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(6, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        main_table->setVerticalHeaderItem(7, __qtablewidgetitem8);
        main_table->setObjectName(QString::fromUtf8("main_table"));
        main_table->setGeometry(QRect(560, 130, 151, 271));
        main_table->setStyleSheet(QString::fromUtf8("background-color: rgb(238, 238, 236);"));
        main_table->setGridStyle(Qt::SolidLine);
        main_table->horizontalHeader()->setDefaultSectionSize(145);
        label_2 = new QLabel(MainPage);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(390, 140, 101, 17));
        QFont font;
        font.setPointSize(14);
        label_2->setFont(font);
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(56, 51, 139);"));
        label_3 = new QLabel(MainPage);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(310, 190, 81, 17));
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        getinfo = new QPushButton(MainPage);
        getinfo->setObjectName(QString::fromUtf8("getinfo"));
        getinfo->setGeometry(QRect(140, 260, 121, 31));
        getinfo->setStyleSheet(QString::fromUtf8("background-color: rgb(237, 212, 0);\n"
"color: rgb(239, 41, 41);"));
        countryHome = new QTextBrowser(MainPage);
        countryHome->setObjectName(QString::fromUtf8("countryHome"));
        countryHome->setGeometry(QRect(390, 220, 141, 31));
        countryHome->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        addno = new QPushButton(MainPage);
        addno->setObjectName(QString::fromUtf8("addno"));
        addno->setGeometry(QRect(140, 210, 121, 31));
        addno->setStyleSheet(QString::fromUtf8("background-color: rgb(237, 212, 0);\n"
"color: rgb(239, 41, 41);"));
        btn_HomePrev = new QPushButton(MainPage);
        btn_HomePrev->setObjectName(QString::fromUtf8("btn_HomePrev"));
        btn_HomePrev->setGeometry(QRect(370, 430, 61, 25));
        aadharHome = new QTextBrowser(MainPage);
        aadharHome->setObjectName(QString::fromUtf8("aadharHome"));
        aadharHome->setGeometry(QRect(390, 340, 141, 31));
        aadharHome->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        history = new QPushButton(MainPage);
        history->setObjectName(QString::fromUtf8("history"));
        history->setGeometry(QRect(140, 410, 121, 31));
        history->setStyleSheet(QString::fromUtf8("background-color: rgb(237, 212, 0);\n"
"color: rgb(239, 41, 41);"));
        label_img = new QLabel(MainPage);
        label_img->setObjectName(QString::fromUtf8("label_img"));
        label_img->setGeometry(QRect(390, 0, 141, 121));
        nameHome = new QTextBrowser(MainPage);
        nameHome->setObjectName(QString::fromUtf8("nameHome"));
        nameHome->setGeometry(QRect(390, 260, 141, 31));
        nameHome->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_39 = new QLabel(MainPage);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(310, 220, 81, 31));
        label_39->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        companyHome = new QTextBrowser(MainPage);
        companyHome->setObjectName(QString::fromUtf8("companyHome"));
        companyHome->setGeometry(QRect(390, 300, 141, 31));
        companyHome->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_40 = new QLabel(MainPage);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(310, 310, 71, 17));
        label_40->setStyleSheet(QString::fromUtf8("color: rgb(95, 63, 63);\n"
""));
        homePage_update = new QPushButton(MainPage);
        homePage_update->setObjectName(QString::fromUtf8("homePage_update"));
        homePage_update->setGeometry(QRect(470, 430, 61, 25));
        label_42 = new QLabel(MainPage);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(370, 470, 91, 17));
        label_43 = new QLabel(MainPage);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(550, 470, 61, 17));
        totContacts = new QLabel(MainPage);
        totContacts->setObjectName(QString::fromUtf8("totContacts"));
        totContacts->setGeometry(QRect(470, 470, 71, 17));
        homePageNo = new QLabel(MainPage);
        homePageNo->setObjectName(QString::fromUtf8("homePageNo"));
        homePageNo->setGeometry(QRect(620, 470, 51, 16));
        stackedWidget->addWidget(MainPage);
        delno->raise();
        addno->raise();
        update->raise();
        label->raise();
        tableView->raise();
        btn_HomeNext->raise();
        label_2->raise();
        getinfo->raise();
        label_3->raise();
        aadharHome->raise();
        label_4->raise();
        label_6->raise();
        label_5->raise();
        contactNo->raise();
        addressHome->raise();
        countryHome->raise();
        history->raise();
        label_img->raise();
        nameHome->raise();
        label_39->raise();
        companyHome->raise();
        label_40->raise();
        homePage_update->raise();
        btn_HomePrev->raise();
        main_table->raise();
        label_42->raise();
        label_43->raise();
        totContacts->raise();
        homePageNo->raise();
        PageDelNo = new QWidget();
        PageDelNo->setObjectName(QString::fromUtf8("PageDelNo"));
        label_32 = new QLabel(PageDelNo);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(310, 70, 211, 41));
        QFont font1;
        font1.setPointSize(20);
        label_32->setFont(font1);
        label_32->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_32->setAlignment(Qt::AlignCenter);
        tableView_4 = new QTableView(PageDelNo);
        tableView_4->setObjectName(QString::fromUtf8("tableView_4"));
        tableView_4->setGeometry(QRect(190, 130, 461, 321));
        tableView_4->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        btn_delSubmit = new QPushButton(PageDelNo);
        btn_delSubmit->setObjectName(QString::fromUtf8("btn_delSubmit"));
        btn_delSubmit->setGeometry(QRect(380, 380, 89, 25));
        btn_delSubmit->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        label_31 = new QLabel(PageDelNo);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(250, 260, 67, 17));
        delNoCode = new QLineEdit(PageDelNo);
        delNoCode->setObjectName(QString::fromUtf8("delNoCode"));
        delNoCode->setGeometry(QRect(360, 190, 71, 31));
        delNoCode->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        delNoStatus = new QTextBrowser(PageDelNo);
        delNoStatus->setObjectName(QString::fromUtf8("delNoStatus"));
        delNoStatus->setGeometry(QRect(360, 250, 131, 31));
        delNoStatus->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);\n"
"color: rgb(56, 51, 139);"));
        label_30 = new QLabel(PageDelNo);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(500, 170, 61, 21));
        QFont font2;
        font2.setPointSize(11);
        label_30->setFont(font2);
        label_30->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        label_33 = new QLabel(PageDelNo);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(240, 320, 81, 21));
        label_33->setFont(font2);
        pushButton_15 = new QPushButton(PageDelNo);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(330, 480, 141, 25));
        label_44 = new QLabel(PageDelNo);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(350, 170, 101, 21));
        label_44->setFont(font2);
        label_44->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        delNumber = new QLineEdit(PageDelNo);
        delNumber->setObjectName(QString::fromUtf8("delNumber"));
        delNumber->setGeometry(QRect(460, 190, 141, 31));
        delNumber->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_45 = new QLabel(PageDelNo);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(240, 196, 91, 21));
        reconfirmCode = new QLineEdit(PageDelNo);
        reconfirmCode->setObjectName(QString::fromUtf8("reconfirmCode"));
        reconfirmCode->setGeometry(QRect(360, 320, 71, 31));
        reconfirmCode->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_46 = new QLabel(PageDelNo);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(500, 300, 61, 21));
        label_46->setFont(font2);
        label_46->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        reconfirmNo = new QLineEdit(PageDelNo);
        reconfirmNo->setObjectName(QString::fromUtf8("reconfirmNo"));
        reconfirmNo->setGeometry(QRect(460, 320, 141, 31));
        reconfirmNo->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_47 = new QLabel(PageDelNo);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(350, 300, 101, 21));
        label_47->setFont(font2);
        label_47->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        stackedWidget->addWidget(PageDelNo);
        PageAddNo = new QWidget();
        PageAddNo->setObjectName(QString::fromUtf8("PageAddNo"));
        label_7 = new QLabel(PageAddNo);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(310, 30, 211, 41));
        label_7->setFont(font1);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_7->setAlignment(Qt::AlignCenter);
        noType = new QComboBox(PageAddNo);
        noType->addItem(QString());
        noType->addItem(QString());
        noType->setObjectName(QString::fromUtf8("noType"));
        noType->setGeometry(QRect(410, 90, 151, 31));
        code = new QTextEdit(PageAddNo);
        code->setObjectName(QString::fromUtf8("code"));
        code->setGeometry(QRect(410, 130, 151, 31));
        code->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        company = new QTextEdit(PageAddNo);
        company->setObjectName(QString::fromUtf8("company"));
        company->setGeometry(QRect(410, 210, 151, 31));
        company->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        vipDigits = new QTextEdit(PageAddNo);
        vipDigits->setObjectName(QString::fromUtf8("vipDigits"));
        vipDigits->setGeometry(QRect(410, 250, 151, 31));
        vipDigits->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        aadharNo = new QTextEdit(PageAddNo);
        aadharNo->setObjectName(QString::fromUtf8("aadharNo"));
        aadharNo->setGeometry(QRect(410, 330, 151, 31));
        aadharNo->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_11 = new QLabel(PageAddNo);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(320, 300, 51, 17));
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        label_8 = new QLabel(PageAddNo);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(300, 90, 101, 31));
        label_8->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        label_code = new QLabel(PageAddNo);
        label_code->setObjectName(QString::fromUtf8("label_code"));
        label_code->setGeometry(QRect(320, 140, 51, 20));
        label_code->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        label_10 = new QLabel(PageAddNo);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(310, 330, 81, 31));
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        label_12 = new QLabel(PageAddNo);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(320, 380, 67, 17));
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        addNoSubmit = new QPushButton(PageAddNo);
        addNoSubmit->setObjectName(QString::fromUtf8("addNoSubmit"));
        addNoSubmit->setGeometry(QRect(440, 410, 89, 25));
        addNoSubmit->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        pushButton_16 = new QPushButton(PageAddNo);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(350, 480, 141, 25));
        name = new QTextEdit(PageAddNo);
        name->setObjectName(QString::fromUtf8("name"));
        name->setGeometry(QRect(410, 290, 151, 31));
        name->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_37 = new QLabel(PageAddNo);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(290, 250, 111, 31));
        label_37->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        address = new QTextEdit(PageAddNo);
        address->setObjectName(QString::fromUtf8("address"));
        address->setGeometry(QRect(410, 370, 151, 31));
        address->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_41 = new QLabel(PageAddNo);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(310, 210, 81, 21));
        label_41->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        code_Name = new QTextEdit(PageAddNo);
        code_Name->setObjectName(QString::fromUtf8("code_Name"));
        code_Name->setGeometry(QRect(410, 170, 151, 31));
        code_Name->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_codeName = new QLabel(PageAddNo);
        label_codeName->setObjectName(QString::fromUtf8("label_codeName"));
        label_codeName->setGeometry(QRect(300, 170, 101, 31));
        label_codeName->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        stackedWidget->addWidget(PageAddNo);
        PageGetInfo = new QWidget();
        PageGetInfo->setObjectName(QString::fromUtf8("PageGetInfo"));
        label_13 = new QLabel(PageGetInfo);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(290, 10, 241, 41));
        QFont font3;
        font3.setPointSize(17);
        label_13->setFont(font3);
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_14 = new QLabel(PageGetInfo);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(310, 110, 141, 21));
        QFont font4;
        font4.setPointSize(12);
        label_14->setFont(font4);
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(32, 74, 135);"));
        infoSearch = new QLineEdit(PageGetInfo);
        infoSearch->setObjectName(QString::fromUtf8("infoSearch"));
        infoSearch->setGeometry(QRect(280, 80, 211, 31));
        infoSearch->setStyleSheet(QString::fromUtf8("background-color: rgb(238, 238, 236);"));
        pushButton_18 = new QPushButton(PageGetInfo);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(300, 490, 141, 25));
        label_51 = new QLabel(PageGetInfo);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(160, 220, 81, 31));
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        label_15 = new QLabel(PageGetInfo);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(240, 150, 91, 17));
        label_17 = new QLabel(PageGetInfo);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(160, 350, 71, 17));
        label_17->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        contactNo_get = new QTextBrowser(PageGetInfo);
        contactNo_get->setObjectName(QString::fromUtf8("contactNo_get"));
        contactNo_get->setGeometry(QRect(250, 180, 141, 31));
        contactNo_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        totContacts_get = new QLabel(PageGetInfo);
        totContacts_get->setObjectName(QString::fromUtf8("totContacts_get"));
        totContacts_get->setGeometry(QRect(250, 430, 51, 17));
        label_19 = new QLabel(PageGetInfo);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(170, 270, 51, 21));
        label_19->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        tableView_2 = new QTableView(PageGetInfo);
        tableView_2->setObjectName(QString::fromUtf8("tableView_2"));
        tableView_2->setGeometry(QRect(150, 60, 451, 411));
        tableView_2->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        country_get = new QTextBrowser(PageGetInfo);
        country_get->setObjectName(QString::fromUtf8("country_get"));
        country_get->setGeometry(QRect(250, 220, 141, 31));
        country_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_18 = new QLabel(PageGetInfo);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(160, 186, 81, 21));
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        label_16 = new QLabel(PageGetInfo);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(170, 390, 61, 17));
        label_16->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        address_get = new QTextBrowser(PageGetInfo);
        address_get->setObjectName(QString::fromUtf8("address_get"));
        address_get->setGeometry(QRect(250, 380, 141, 31));
        address_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        aadhar_get = new QTextBrowser(PageGetInfo);
        aadhar_get->setObjectName(QString::fromUtf8("aadhar_get"));
        aadhar_get->setGeometry(QRect(250, 340, 141, 31));
        aadhar_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_50 = new QLabel(PageGetInfo);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(300, 430, 61, 17));
        company_get = new QTextBrowser(PageGetInfo);
        company_get->setObjectName(QString::fromUtf8("company_get"));
        company_get->setGeometry(QRect(250, 300, 141, 31));
        company_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        name_get = new QTextBrowser(PageGetInfo);
        name_get->setObjectName(QString::fromUtf8("name_get"));
        name_get->setGeometry(QRect(250, 260, 141, 31));
        name_get->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        getInfo_table = new QTableWidget(PageGetInfo);
        if (getInfo_table->columnCount() < 1)
            getInfo_table->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        getInfo_table->setHorizontalHeaderItem(0, __qtablewidgetitem9);
        if (getInfo_table->rowCount() < 8)
            getInfo_table->setRowCount(8);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(0, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(1, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(2, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(3, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(4, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(5, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(6, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        getInfo_table->setVerticalHeaderItem(7, __qtablewidgetitem17);
        getInfo_table->setObjectName(QString::fromUtf8("getInfo_table"));
        getInfo_table->setGeometry(QRect(420, 150, 151, 271));
        getInfo_table->setStyleSheet(QString::fromUtf8("background-color: rgb(238, 238, 236);     T  R R"));
        getInfo_table->horizontalHeader()->setDefaultSectionSize(145);
        label_48 = new QLabel(PageGetInfo);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(160, 310, 71, 17));
        label_48->setStyleSheet(QString::fromUtf8("color: rgb(164, 0, 0);"));
        btn_getInfoNext = new QPushButton(PageGetInfo);
        btn_getInfoNext->setObjectName(QString::fromUtf8("btn_getInfoNext"));
        btn_getInfoNext->setGeometry(QRect(500, 430, 61, 25));
        btn_getInfoNext->setStyleSheet(QString::fromUtf8("border-color: rgb(0, 0, 0);"));
        label_49 = new QLabel(PageGetInfo);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(150, 430, 91, 17));
        btn_getInfoPrev = new QPushButton(PageGetInfo);
        btn_getInfoPrev->setObjectName(QString::fromUtf8("btn_getInfoPrev"));
        btn_getInfoPrev->setGeometry(QRect(420, 430, 61, 25));
        btn_getInfoPrev->setStyleSheet(QString::fromUtf8("border-color: rgb(0, 0, 0);"));
        getInfoPageNo = new QLabel(PageGetInfo);
        getInfoPageNo->setObjectName(QString::fromUtf8("getInfoPageNo"));
        getInfoPageNo->setGeometry(QRect(380, 430, 41, 17));
        stackedWidget->addWidget(PageGetInfo);
        tableView_2->raise();
        label_13->raise();
        label_14->raise();
        infoSearch->raise();
        pushButton_18->raise();
        label_51->raise();
        label_15->raise();
        label_17->raise();
        contactNo_get->raise();
        totContacts_get->raise();
        label_19->raise();
        country_get->raise();
        label_18->raise();
        label_16->raise();
        address_get->raise();
        aadhar_get->raise();
        label_50->raise();
        company_get->raise();
        name_get->raise();
        getInfo_table->raise();
        label_48->raise();
        btn_getInfoNext->raise();
        label_49->raise();
        btn_getInfoPrev->raise();
        getInfoPageNo->raise();
        PageUpdate = new QWidget();
        PageUpdate->setObjectName(QString::fromUtf8("PageUpdate"));
        label_20 = new QLabel(PageUpdate);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(300, 10, 211, 41));
        label_20->setFont(font1);
        label_20->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_20->setAlignment(Qt::AlignCenter);
        tableView_3 = new QTableView(PageUpdate);
        tableView_3->setObjectName(QString::fromUtf8("tableView_3"));
        tableView_3->setGeometry(QRect(160, 140, 451, 361));
        tableView_3->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        submit_update = new QPushButton(PageUpdate);
        submit_update->setObjectName(QString::fromUtf8("submit_update"));
        submit_update->setGeometry(QRect(390, 450, 89, 25));
        submit_update->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        label_26 = new QLabel(PageUpdate);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(310, 80, 141, 21));
        label_26->setFont(font2);
        label_26->setStyleSheet(QString::fromUtf8("color: rgb(138, 226, 52);E"));
        searchNo_update = new QLineEdit(PageUpdate);
        searchNo_update->setObjectName(QString::fromUtf8("searchNo_update"));
        searchNo_update->setGeometry(QRect(280, 100, 181, 31));
        searchNo_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        status_update = new QTextBrowser(PageUpdate);
        status_update->setObjectName(QString::fromUtf8("status_update"));
        status_update->setGeometry(QRect(480, 100, 111, 31));
        status_update->setStyleSheet(QString::fromUtf8("color: rgb(253, 173, 48);"));
        label_27 = new QLabel(PageUpdate);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(510, 80, 51, 20));
        label_27->setStyleSheet(QString::fromUtf8("color: rgb(138, 226, 52);E"));
        label_28 = new QLabel(PageUpdate);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(280, 150, 231, 20));
        QFont font5;
        font5.setPointSize(13);
        label_28->setFont(font5);
        label_28->setStyleSheet(QString::fromUtf8("color: rgb(56, 51, 139);"));
        pushButton_17 = new QPushButton(PageUpdate);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(300, 510, 141, 25));
        label_53 = new QLabel(PageUpdate);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(270, 310, 71, 17));
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        label_21 = new QLabel(PageUpdate);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(280, 410, 67, 17));
        label_21->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        label_23 = new QLabel(PageUpdate);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(270, 360, 71, 17));
        label_23->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        label_52 = new QLabel(PageUpdate);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(270, 200, 81, 31));
        label_52->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        label_22 = new QLabel(PageUpdate);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(280, 250, 51, 31));
        label_22->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        searchCode_update = new QLineEdit(PageUpdate);
        searchCode_update->setObjectName(QString::fromUtf8("searchCode_update"));
        searchCode_update->setGeometry(QRect(190, 100, 71, 31));
        searchCode_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_updateCode = new QLabel(PageUpdate);
        label_updateCode->setObjectName(QString::fromUtf8("label_updateCode"));
        label_updateCode->setGeometry(QRect(160, 80, 141, 21));
        label_updateCode->setFont(font2);
        label_updateCode->setStyleSheet(QString::fromUtf8("color: rgb(138, 226, 52);E"));
        country_update = new QLineEdit(PageUpdate);
        country_update->setObjectName(QString::fromUtf8("country_update"));
        country_update->setGeometry(QRect(370, 200, 141, 31));
        country_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        name_update = new QLineEdit(PageUpdate);
        name_update->setObjectName(QString::fromUtf8("name_update"));
        name_update->setGeometry(QRect(370, 250, 141, 31));
        name_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        company_update = new QLineEdit(PageUpdate);
        company_update->setObjectName(QString::fromUtf8("company_update"));
        company_update->setGeometry(QRect(370, 300, 141, 31));
        company_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        aadhar_update = new QLineEdit(PageUpdate);
        aadhar_update->setObjectName(QString::fromUtf8("aadhar_update"));
        aadhar_update->setGeometry(QRect(370, 350, 141, 31));
        aadhar_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        address_update = new QTextEdit(PageUpdate);
        address_update->setObjectName(QString::fromUtf8("address_update"));
        address_update->setGeometry(QRect(370, 400, 141, 31));
        address_update->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        stackedWidget->addWidget(PageUpdate);
        PageHistory = new QWidget();
        PageHistory->setObjectName(QString::fromUtf8("PageHistory"));
        label_34 = new QLabel(PageHistory);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(260, 20, 211, 41));
        QFont font6;
        font6.setPointSize(21);
        label_34->setFont(font6);
        label_34->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_34->setAlignment(Qt::AlignCenter);
        historyTable = new QTableWidget(PageHistory);
        if (historyTable->columnCount() < 3)
            historyTable->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        historyTable->setHorizontalHeaderItem(0, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        historyTable->setHorizontalHeaderItem(1, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        historyTable->setHorizontalHeaderItem(2, __qtablewidgetitem20);
        if (historyTable->rowCount() < 10)
            historyTable->setRowCount(10);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(0, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(1, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(2, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(3, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(4, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(5, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(6, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(7, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(8, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        historyTable->setVerticalHeaderItem(9, __qtablewidgetitem30);
        historyTable->setObjectName(QString::fromUtf8("historyTable"));
        historyTable->setGeometry(QRect(340, 100, 341, 371));
        historyTable->setStyleSheet(QString::fromUtf8("background-color: rgb(238, 238, 236);"));
        historyTable->horizontalHeader()->setMinimumSectionSize(66);
        historyTable->horizontalHeader()->setDefaultSectionSize(112);
        historyTable->verticalHeader()->setDefaultSectionSize(30);
        BtnPrevHistory = new QPushButton(PageHistory);
        BtnPrevHistory->setObjectName(QString::fromUtf8("BtnPrevHistory"));
        BtnPrevHistory->setGeometry(QRect(350, 430, 89, 25));
        BtnPrevHistory->setStyleSheet(QString::fromUtf8("border-color: rgb(0, 0, 0);"));
        BtnNextHistory = new QPushButton(PageHistory);
        BtnNextHistory->setObjectName(QString::fromUtf8("BtnNextHistory"));
        BtnNextHistory->setGeometry(QRect(580, 430, 89, 25));
        BtnNextHistory->setStyleSheet(QString::fromUtf8("border-color: rgb(0, 0, 0);"));
        retriveType = new QComboBox(PageHistory);
        retriveType->addItem(QString());
        retriveType->addItem(QString());
        retriveType->addItem(QString());
        retriveType->setObjectName(QString::fromUtf8("retriveType"));
        retriveType->setGeometry(QRect(190, 144, 131, 31));
        label_35 = new QLabel(PageHistory);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(60, 150, 101, 17));
        label_35->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        lowerTime = new QLineEdit(PageHistory);
        lowerTime->setObjectName(QString::fromUtf8("lowerTime"));
        lowerTime->setGeometry(QRect(190, 190, 131, 31));
        lowerTime->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        upperTimeOrN = new QLineEdit(PageHistory);
        upperTimeOrN->setObjectName(QString::fromUtf8("upperTimeOrN"));
        upperTimeOrN->setGeometry(QRect(190, 240, 131, 31));
        upperTimeOrN->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        labelTime = new QLabel(PageHistory);
        labelTime->setObjectName(QString::fromUtf8("labelTime"));
        labelTime->setGeometry(QRect(60, 200, 121, 20));
        labelTime->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        label_N = new QLabel(PageHistory);
        label_N->setObjectName(QString::fromUtf8("label_N"));
        label_N->setGeometry(QRect(60, 250, 131, 17));
        label_N->setStyleSheet(QString::fromUtf8("color: rgb(115, 210, 22);"));
        BtnHistorySubmit = new QPushButton(PageHistory);
        BtnHistorySubmit->setObjectName(QString::fromUtf8("BtnHistorySubmit"));
        BtnHistorySubmit->setGeometry(QRect(140, 300, 89, 25));
        BtnHistorySubmit->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        pushButton_14 = new QPushButton(PageHistory);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(280, 510, 141, 25));
        label_pageNo = new QLabel(PageHistory);
        label_pageNo->setObjectName(QString::fromUtf8("label_pageNo"));
        label_pageNo->setGeometry(QRect(490, 450, 41, 16));
        label_pageNo->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(PageHistory);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(480, 430, 61, 21));
        label_36 = new QLabel(PageHistory);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(530, 470, 101, 21));
        label_36->setStyleSheet(QString::fromUtf8("color: rgb(138, 226, 52);"));
        label_totalEntries = new QLabel(PageHistory);
        label_totalEntries->setObjectName(QString::fromUtf8("label_totalEntries"));
        label_totalEntries->setGeometry(QRect(640, 470, 41, 21));
        label_totalEntries->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        stackedWidget->addWidget(PageHistory);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label_54 = new QLabel(page);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(270, 240, 81, 31));
        label_54->setFont(font2);
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        tableView_5 = new QTableView(page);
        tableView_5->setObjectName(QString::fromUtf8("tableView_5"));
        tableView_5->setGeometry(QRect(210, 130, 361, 241));
        tableView_5->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        login_submit = new QPushButton(page);
        login_submit->setObjectName(QString::fromUtf8("login_submit"));
        login_submit->setGeometry(QRect(420, 300, 89, 25));
        login_submit->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        login_pswd = new QLineEdit(page);
        login_pswd->setObjectName(QString::fromUtf8("login_pswd"));
        login_pswd->setGeometry(QRect(370, 240, 141, 31));
        login_pswd->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_57 = new QLabel(page);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(280, 180, 61, 31));
        label_57->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        login_userId = new QLineEdit(page);
        login_userId->setObjectName(QString::fromUtf8("login_userId"));
        login_userId->setGeometry(QRect(370, 180, 141, 31));
        login_userId->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_55 = new QLabel(page);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(290, 70, 211, 41));
        label_55->setFont(font1);
        label_55->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_55->setAlignment(Qt::AlignCenter);
        pushButton_19 = new QPushButton(page);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(320, 420, 141, 25));
        loginInfo_update = new QPushButton(page);
        loginInfo_update->setObjectName(QString::fromUtf8("loginInfo_update"));
        loginInfo_update->setGeometry(QRect(260, 300, 131, 25));
        loginInfo_update->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        stackedWidget->addWidget(page);
        tableView_5->raise();
        label_57->raise();
        login_userId->raise();
        login_pswd->raise();
        login_submit->raise();
        label_54->raise();
        label_55->raise();
        pushButton_19->raise();
        loginInfo_update->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_58 = new QLabel(page_2);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(270, 210, 81, 31));
        label_58->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        tableView_6 = new QTableView(page_2);
        tableView_6->setObjectName(QString::fromUtf8("tableView_6"));
        tableView_6->setGeometry(QRect(220, 160, 351, 241));
        tableView_6->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207, 250);"));
        login_userId_new = new QLineEdit(page_2);
        login_userId_new->setObjectName(QString::fromUtf8("login_userId_new"));
        login_userId_new->setGeometry(QRect(380, 210, 141, 31));
        login_userId_new->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        login_pswd_new = new QLineEdit(page_2);
        login_pswd_new->setObjectName(QString::fromUtf8("login_pswd_new"));
        login_pswd_new->setGeometry(QRect(380, 270, 141, 31));
        login_pswd_new->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_56 = new QLabel(page_2);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(260, 270, 101, 21));
        label_56->setFont(font2);
        label_56->setStyleSheet(QString::fromUtf8("color: rgb(239, 41, 41);"));
        loginUpdate_submit = new QPushButton(page_2);
        loginUpdate_submit->setObjectName(QString::fromUtf8("loginUpdate_submit"));
        loginUpdate_submit->setGeometry(QRect(350, 340, 89, 25));
        loginUpdate_submit->setStyleSheet(QString::fromUtf8("background-color: rgb(74, 239, 209);"));
        label_59 = new QLabel(page_2);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(240, 100, 311, 41));
        label_59->setFont(font3);
        label_59->setStyleSheet(QString::fromUtf8("color: rgb(252, 233, 79);"));
        label_59->setAlignment(Qt::AlignCenter);
        pushButton_20 = new QPushButton(page_2);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(310, 430, 141, 25));
        stackedWidget->addWidget(page_2);
        tableView_6->raise();
        login_userId_new->raise();
        label_56->raise();
        loginUpdate_submit->raise();
        login_pswd_new->raise();
        label_58->raise();
        label_59->raise();
        pushButton_20->raise();
        msg = new QTextBrowser(centralwidget);
        msg->setObjectName(QString::fromUtf8("msg"));
        msg->setGeometry(QRect(540, 0, 251, 31));
        msg->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(470, 0, 67, 31));
        label_38->setStyleSheet(QString::fromUtf8("color: rgb(252, 175, 62);"));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 799, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        delno->setText(QApplication::translate("MainWindow", "Delete Number", nullptr));
        btn_HomeNext->setText(QApplication::translate("MainWindow", "Next", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Aadhar No", nullptr));
        update->setText(QApplication::translate("MainWindow", "Update", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Name", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Address", nullptr));
        label->setText(QApplication::translate("MainWindow", "MENU", nullptr));
        QTableWidgetItem *___qtablewidgetitem = main_table->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "Contact No", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Information", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Contact No", nullptr));
        getinfo->setText(QApplication::translate("MainWindow", "Get Info", nullptr));
        countryHome->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        addno->setText(QApplication::translate("MainWindow", "Add Number", nullptr));
        btn_HomePrev->setText(QApplication::translate("MainWindow", "Previous", nullptr));
        history->setText(QApplication::translate("MainWindow", "History", nullptr));
        label_img->setText(QApplication::translate("MainWindow", "LOGO", nullptr));
        label_39->setText(QApplication::translate("MainWindow", "State/Area", nullptr));
        label_40->setText(QApplication::translate("MainWindow", "Company", nullptr));
        homePage_update->setText(QApplication::translate("MainWindow", "Update", nullptr));
        label_42->setText(QApplication::translate("MainWindow", "Total Entries:", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "Page No:", nullptr));
        totContacts->setText(QApplication::translate("MainWindow", "0", nullptr));
        homePageNo->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "DELETE NUMBER", nullptr));
        btn_delSubmit->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Status", nullptr));
        delNoStatus->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Not Available.</p></body></html>", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "Number", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "Reconfirm", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_44->setText(QApplication::translate("MainWindow", "Country Code", nullptr));
        label_45->setText(QApplication::translate("MainWindow", "Enter Details", nullptr));
        label_46->setText(QApplication::translate("MainWindow", "Number", nullptr));
        label_47->setText(QApplication::translate("MainWindow", "Country Code", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "ADD NUMBER", nullptr));
        noType->setItemText(0, QApplication::translate("MainWindow", "Mobile Number", nullptr));
        noType->setItemText(1, QApplication::translate("MainWindow", "Landline Number", nullptr));

        company->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Name*", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Number Type*", nullptr));
        label_code->setText(QApplication::translate("MainWindow", "Code*", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Aadhar No*", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Address", nullptr));
        addNoSubmit->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        pushButton_16->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "VIP Digits If Any", nullptr));
        label_41->setText(QApplication::translate("MainWindow", "Company*", nullptr));
        label_codeName->setText(QApplication::translate("MainWindow", "Country Name", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "GET INFORMATION", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Search For Number", nullptr));
        pushButton_18->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_51->setText(QApplication::translate("MainWindow", "State/Area", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "Information", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Aadhar No", nullptr));
        totContacts_get->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "Name", nullptr));
        country_get->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Contact No", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Address", nullptr));
        label_50->setText(QApplication::translate("MainWindow", "Page No:", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = getInfo_table->horizontalHeaderItem(0);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Available Numbers", nullptr));
        label_48->setText(QApplication::translate("MainWindow", "Company", nullptr));
        btn_getInfoNext->setText(QApplication::translate("MainWindow", "Next", nullptr));
        label_49->setText(QApplication::translate("MainWindow", "Total Entries:", nullptr));
        btn_getInfoPrev->setText(QApplication::translate("MainWindow", "Previous", nullptr));
        getInfoPageNo->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "UPDATE", nullptr));
        submit_update->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Search For Number", nullptr));
        status_update->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Not Available.</p></body></html>", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Status", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "UPDATE YOUR INFORMATION", nullptr));
        pushButton_17->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_53->setText(QApplication::translate("MainWindow", "Company", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Address", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Aadhar No", nullptr));
        label_52->setText(QApplication::translate("MainWindow", "State/Area", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Name", nullptr));
        label_updateCode->setText(QApplication::translate("MainWindow", "Country/Area Code", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "History", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = historyTable->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "Number", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = historyTable->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "Action", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = historyTable->horizontalHeaderItem(2);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "Time", nullptr));
        BtnPrevHistory->setText(QApplication::translate("MainWindow", "Previous", nullptr));
        BtnNextHistory->setText(QApplication::translate("MainWindow", "Next", nullptr));
        retriveType->setItemText(0, QApplication::translate("MainWindow", "Retrive N Units From Input Time", nullptr));
        retriveType->setItemText(1, QApplication::translate("MainWindow", "Retrive All Units Between Input Time Range", nullptr));
        retriveType->setItemText(2, QApplication::translate("MainWindow", "Retrive All History", nullptr));

        label_35->setText(QApplication::translate("MainWindow", "Retrive Type", nullptr));
        labelTime->setText(QApplication::translate("MainWindow", "Enter Time", nullptr));
        label_N->setText(QApplication::translate("MainWindow", "Enter Value Of 'N'", nullptr));
        BtnHistorySubmit->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        pushButton_14->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_pageNo->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Page No", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "Total Entries :", nullptr));
        label_totalEntries->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_54->setText(QApplication::translate("MainWindow", "Password", nullptr));
        login_submit->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        label_57->setText(QApplication::translate("MainWindow", "User Id", nullptr));
        label_55->setText(QApplication::translate("MainWindow", "LOG IN", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        loginInfo_update->setText(QApplication::translate("MainWindow", "Update login info", nullptr));
        label_58->setText(QApplication::translate("MainWindow", "New User Id", nullptr));
        label_56->setText(QApplication::translate("MainWindow", "New Password", nullptr));
        loginUpdate_submit->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        label_59->setText(QApplication::translate("MainWindow", "UPDATE LOGIN CREDENTIALS", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "GOTO MAIN MENU", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "Message : ", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
